language: java
jdk:
 - oraclejdk8
addons:
  sonarcloud:
    organization: "food-limit"
    token:
      secure: $SONAR_TOKEN
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: food-limit-api
