language: java
jdk:
 - oraclejdk8
addons:
  sonarcloud:
    organization: "food-limit"
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $GITHUB_TOKEN
script:
  - ./mvnw test
  - sonar-scanner
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: food-limit-api

