language: java
jdk:
 - oraclejdk8
addons:
  sonarcloud:
    organization: "food-limit"
    token:
      secure: $SONAR_TOKEN
    github_token:
      secure: $GITHUB_TOKEN
script:
  - sonar-scanner
deploy:
 provider: heroku
 api-key:
  secure: $HEROKU_API_KEY
 app: food-limit-api
