spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test;DB_CLOSE_ON_EXIT=FALSE"
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: test
