app:
  secret: the_secret
  token-validity-in-seconds: 2592000

security:
  ignored:
    - none

spring:
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
  resources:
    add-mappings: false
