app:
  secret: the_secret
  token-validity-in-seconds: 2592000

security:
  ignored:
    - none

spring:
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
  resources:
    add-mappings: false

onesignal:
  url: https://onesignal.com/api/v1/notifications
  api-key: ${ONE_SIGNAL_API_KEY}
  app-id: ${ONE_SIGNAL_APP_ID}
