INSERT INTO PING(TITLE) VALUES ('PONG EN PROD !');

INSERT INTO USER_PROFILE (USERNAME, EMAIL, NAME, PASSWORD) VALUES ('admin', 'admin@foodlimit.fr', 'Admin Admin', '$2a$12$I6nKjXN24kFy6Q1sB5EHUeK/wRe7u7LnPesWUHOPKvGah4eGgygvy');
